import Head from 'next/head';
import ComingSoon from '../app/components/ComingSoon';
import Layout from '../app/components/Layout';
import SocialNetworks from '../app/components/SocialNetworks';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <ComingSoon />
        <SocialNetworks size="4xl" />
      </Layout>
    </>
  );
}
